services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: key_value_store
      POSTGRES_USER: staceylee
      POSTGRES_PASSWORD: Stacey2002*
    ports:
      - "5432:5432"  # Make sure port 5432 is exposed

  # fastapi:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/app
  #   command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db
    entrypoint: ["/bin/bash", "-c", "cd /key_value_store/build && ctest --output-on-failure --build-config Release"]
